version: 2

enable-beta-ecosystems: true # Required to use the Bazel ecosystems

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /tools
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /tools
    schedule:
      interval: weekly
  - package-ecosystem: "bazel" 
    directory: "/devertexwahn" # Location of package manifests
    schedule:
      interval: weekly
