name: Handle Comment Commands
on:
  issue_comment:
    types: [created]

jobs:
  handle-comment:
    # Only run on comments on PRs, and only on commands starting with "@bazel-io ".
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '@bazel-io ')
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Handle @bazel-io commands
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@bc92ee7cd9d5a6cfeef84d5ec13b227a5afd5463
        with:
          # This token needs to be updated annually on Feb 05.
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: 'handle_comment'
